$info = git log -1 --format='%h %cd' --date=format:%Y-%m-%d
$content = "// Generated by build. Update before deployment: git log -1 --format='const BUILD_VERSION = ''%h %cd'';' --date=format:%Y-%m-%d > version.js`nconst BUILD_VERSION = '$info';`n"
Set-Content -Path "$PSScriptRoot\version.js" -Value $content -NoNewline
Write-Host "version.js updated: $info"
